package view;

import java.awt.event.ActionListener;

/**
 *
 * @author andre
 */
public class ViewInstructions extends javax.swing.JFrame {

    
    public ViewInstructions() {
        initComponents();
        setSize(846, 592);
    }
    
    public void addBtnNextListener(ActionListener listenControllers){
        jbNext.addActionListener(listenControllers);
    }
    
    public void addBtnBackListener(ActionListener listenControllers){
        jbBack.addActionListener(listenControllers);
    }
    
    public void addBtnExitInstructionstListener(ActionListener listenControllers){
        jbExitInstructions.addActionListener(listenControllers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbNext = new javax.swing.JButton();
        jbExitInstructions = new javax.swing.JButton();
        jbBack = new javax.swing.JButton();
        jlBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 832, 555));
        setMaximumSize(new java.awt.Dimension(832, 555));
        setMinimumSize(new java.awt.Dimension(832, 555));
        setPreferredSize(new java.awt.Dimension(832, 555));
        setSize(new java.awt.Dimension(832, 555));
        getContentPane().setLayout(null);

        jbNext.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        jbNext.setText("next");
        jbNext.setBorderPainted(false);
        jbNext.setContentAreaFilled(false);
        jbNext.setFocusPainted(false);
        getContentPane().add(jbNext);
        jbNext.setBounds(680, 170, 140, 70);

        jbExitInstructions.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        jbExitInstructions.setText("exit");
        jbExitInstructions.setBorderPainted(false);
        jbExitInstructions.setContentAreaFilled(false);
        jbExitInstructions.setFocusPainted(false);
        jbExitInstructions.setPreferredSize(new java.awt.Dimension(76, 70));
        getContentPane().add(jbExitInstructions);
        jbExitInstructions.setBounds(740, 20, 76, 70);

        jbBack.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        jbBack.setText("back");
        jbBack.setBorderPainted(false);
        jbBack.setContentAreaFilled(false);
        jbBack.setFocusPainted(false);
        getContentPane().add(jbBack);
        jbBack.setBounds(10, 170, 150, 60);

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/instructions1.png"))); // NOI18N
        jlBackground.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlBackground.setAlignmentY(0.0F);
        getContentPane().add(jlBackground);
        jlBackground.setBounds(0, 0, 832, 555);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setJlBackgroundIcon(String imagePath)
    {
        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagePath)));
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbBack;
    private javax.swing.JButton jbExitInstructions;
    private javax.swing.JButton jbNext;
    private javax.swing.JLabel jlBackground;
    // End of variables declaration//GEN-END:variables
}
